### ISSUE TITLE
Custom routes within resource block not working

### ISSUE THREAD

**Issue by jgnagy** [mwpastore/sinja#13]
I'm trying to add a custom route (similar to `get '/top10'` in your README) and I only get 404s trying to access it. Using pry and inspecting the App::routes on the Sinatra application, I can see the route listed as:

```
[#<Mustermann::Concat:(regular:"\\/organizations(?![^\\/])" + sinatra:"/mine")>, [#<UnboundMethod: Authify::API::Services::API#`block in registered' condition>], #<Proc:0x007fc26c3ab048@/Users/jgnagy/.rvm/gems/ruby-2.3.1/gems/sinatra-2.0.0.beta2/lib/sinatra/base.rb:1643>]
```

The goal with the above is to add a custom route @ `/organizations/mine` on an otherwise normal {json:api} resource `/organizations`.

I've modified my simplified test-api to duplicate the issue: https://github.com/jgnagy/test-api/blob/master/lib/test/api.rb

In the test-api app above, the custom route _should be_ `/testkeys/foo`, but hitting that with:

```shell
curl -i -H 'Accept: application/vnd.api+json' -H 'Content-Type: application/vnd.api+json' http://localhost:9292/testkeys/foo
```

yields:

```plaintext
HTTP/1.1 404 Not Found
Content-Type: application/vnd.api+json
X-Cascade: pass
Content-Length: 141
Server: WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26)
Date: Wed, 15 Feb 2017 15:43:49 GMT
Connection: Keep-Alive

{
  "errors": [
    {
      "id": "bbf08504-d69f-44d5-bb94-b3d84d5e4911",
      "title": "Not Found Error",
      "status": "404"
    }
  ]
}
```

I added a vanilla `/bar` namespace and tested a `/baz` route and that works as expected:

```shell
curl -i -H 'Accept: application/vnd.api+json' -H 'Content-Type: application/vnd.api+json' http://localhost:9292/bar/baz
```

returning:

```plaintext
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json
Content-Length: 519
Server: WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26)
Date: Wed, 15 Feb 2017 15:34:47 GMT
Connection: Keep-Alive

{
  "data": [
    {
      "type": "testkeys",
      "id": "11",
      "attributes": {
        "name": "A Key",
        "created-at": "2017-02-15 07:34:47 -0800"
      },
      "links": {
        "self": "/testkeys/11"
      }
    },
    {
      "type": "testkeys",
      "id": "12",
      "attributes": {
        "name": "A Key",
        "created-at": "2017-02-15 07:34:47 -0800"
      },
      "links": {
        "self": "/testkeys/12"
      }
    }
  ],
  "jsonapi": {
    "version": "1.0"
  },
  "included": [

  ]
}
```

I admit that I might be doing something wrong, but I have more-or-less copied and pasted from the README for this test app.

**Comment by mwpastore** [comment]
Good find. I understand the problem; basically, Sinja thinks "foo" is the primary key of a testkey and (obviously) can't find a testkey with that pk. I hope to have a fix in a bit.

**Comment by mwpastore** [comment]
Hi @jgnagy, thanks for your patience. This turned out to be kind of tricky. It's fixed in master, care to give it another try? [Here](https://github.com/mwpastore/sinja#resources) is the documentation for the new feature, but you shouldn't need to do anything special since testkeys uses an integer primary key.

**Comment by jgnagy** [comment]
Thanks for the fix, @mwpastore! Looks like that worked.

```plaintext
::1 - - [15/Feb/2017:18:43:22 -0800] "GET /organizations/mine HTTP/1.1" 200 83 0.0054
```

Keep up the good work on a fantastic open-source tool!

**Comment by mwpastore** [comment]
Great! You're welcome. :smile:
